name: Manual or API Triggered Pipeline

on:
  workflow_dispatch:  # Enables manual trigger from UI and API

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Sample Command
        run: echo "Pipeline triggered successfully!"
